import React, { useEffect, useMemo, useState } from "react";
// optional admin (safe view) — only used if env vars present
let supabase = null;
if (import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY) {
  // Lazy import to avoid bundling if not used
    // eslint-disable-next-line no-undef
      supabase = (await import("@supabase/supabase-js")).createClient(
          import.meta.env.VITE_SUPABASE_URL,
              import.meta.env.VITE_SUPABASE_ANON_KEY
                );
                }

                const API_BASE = import.meta.env.VITE_API_BASE?.replace(/\/$/, "");

                const CITIES = [
                  { key: "weho", label: "West Hollywood", live: true },
                    { key: "palisades", label: "Pacific Palisades (LADBS)", live: true },
                      { key: "altadena", label: "Altadena (County)", live: false }, // still WIP for ArcGIS; shows friendly msg
                        { key: "beverlyhills", label: "Beverly Hills", live: false }, // waitlist
                        ];

                        function useFetchJson(url, deps = []) {
                          const [state, setState] = useState({ loading: true, data: null, error: null });
                            useEffect(() => {
                                let alive = true;
                                    setState({ loading: true, data: null, error: null });
                                        fetch(url, { headers: { Accept: "application/json" } })
                                              .then((r) => r.json())
                                                    .then((j) => alive && setState({ loading: false, data: j, error: null }))
                                                          .catch((e) => alive && setState({ loading: false, data: null, error: String(e) }));
                                                              return () => { alive = false; };
                                                                }, deps); // eslint-disable-line
                                                                  return state;
                                                                  }

                                                                  function CityCard({ city }) {
                                                                    const recentUrl = `${API_BASE}/${city.key}/recent`;
                                                                      const csvUrl = `${API_BASE}/${city.key}/csv`;
                                                                        const waitlistUrl = `${API_BASE}/waitlist/${city.key}`;
                                                                          const { loading, data, error } = useFetchJson(recentUrl, [recentUrl]);

                                                                            const rows = useMemo(() => {
                                                                                if (!data?.rows) return [];
                                                                                    return data.rows.slice(0, 5);
                                                                                      }, [data]);

                                                                                        const isWaitlist = data?.waitlist === true || city.live === false;

                                                                                          return (
                                                                                              <div className="card">
                                                                                                    <div className="row" style={{ marginBottom: 8 }}>
                                                                                                            <div>
                                                                                                                      <div style={{ fontWeight: 700 }}>{city.label}</div>
                                                                                                                                <div className="mini muted mono">{recentUrl}</div>
                                                                                                                                        </div>
                                                                                                                                                <div className="row" style={{ gap: 8 }}>
                                                                                                                                                          <a className="btn" href={csvUrl}>Download CSV</a>
                                                                                                                                                                  </div>
                                                                                                                                                                        </div>

                                                                                                                                                                              {loading && <div className="muted">Loading recent permits…</div>}
                                                                                                                                                                                    {error && <div className="status-err">Error: {error}</div>}

                                                                                                                                                                                          {!loading && !error && isWaitlist && (
                                                                                                                                                                                                  <div className="muted">
                                                                                                                                                                                                            This city’s API isn’t public yet. You can still subscribe below and we’ll
                                                                                                                                                                                                                      notify you when it’s live.
                                                                                                                                                                                                                                <div className="mini mono" style={{ marginTop: 6 }}>
                                                                                                                                                                                                                                            <a className="btn ghost" href={waitlistUrl}>/waitlist/{city.key}</a>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                          {!loading && !error && rows.length > 0 && (
                                                                                                                                                                                                                                                                                  <div style={{ overflowX: "auto", marginTop: 8 }}>
                                                                                                                                                                                                                                                                                            <table>
                                                                                                                                                                                                                                                                                                        <thead>
                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                      <th>Permit #</th>
                                                                                                                                                                                                                                                                                                                                                      <th>Issued</th>
                                                                                                                                                                                                                                                                                                                                                                      <th>Description</th>
                                                                                                                                                                                                                                                                                                                                                                                      <th>Address</th>
                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                          {rows.map((r, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr key={i}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td className="mono">{r.permit_number || r.pcis_permit || r.permit_no || "—"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td>{(r.issue_date || r.issued_date || "").split("T")[0]}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>{r.work_description || r.permit_description || r.permitsubtype || "—"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>{r.address || r.fulladdress || r.MAIN_ADDRESS || "—"}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mini muted" style={{ marginTop: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Showing {rows.length} of {data.row_count ?? rows.length}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function SubscribeCard() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [email, setEmail] = useState("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const [phone, setPhone] = useState("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const [area, setArea] = useState("weho");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const [status, setStatus] = useState(null);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function submit(e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setStatus("Sending…");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const r = await fetch(`${API_BASE}/subscribe`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              body: JSON.stringify({ email, phone, area }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const j = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (j.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setStatus("✅ Subscribed! We’ll send updates.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setEmail(""); setPhone("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setStatus(`❌ ${j.error || "Failed"}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setStatus(`❌ ${String(err)}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontWeight: 700, marginBottom: 8 }}>Get alerts</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <form onSubmit={submit} className="grid" style={{ gridTemplateColumns: "1fr 1fr" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input placeholder="you@company.com" value={email} onChange={e=>setEmail(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>Phone (optional)</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input placeholder="+1 310…" value={phone} onChange={e=>setPhone(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Area</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select value={area} onChange={e=>setArea(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {CITIES.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="all">All Updates</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="row" style={{ alignItems:"end" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="btn" type="submit">Subscribe</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {status && <div className="mini muted" style={{ marginLeft:8 }}>{status}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function HealthCard() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { loading, data, error } = useFetchJson(`${API_BASE}/health`, []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontWeight: 700 }}>System Health</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="badge">/health</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading && <div className="muted">Checking…</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && <div className="status-err">Error: {error}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {!loading && !error && data && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mini muted">worker: {data.worker_version} • fetched: {new Date(data.fetched_at).toLocaleString()}</div