import React, { useEffect, useState } from "react";
import { fetchRecent, exportCSV, subscribe, waitlist } from "./lib/api";
import RecentTable from "./components/RecentTable";
import SubscribeForm from "./components/SubscribeForm";

type City = "palisades" | "altadena" | "weho" | "beverlyhills";

const CITY_LABELS: Record<City, string> = {
  palisades: "Pacific Palisades (LADBS)",
    altadena: "Altadena (LA County)",
      weho: "West Hollywood (Open Data)",
        beverlyhills: "Beverly Hills (ArcGIS)",
        };

        export default function App() {
          const [city, setCity] = useState<City>("weho");
            const [rows, setRows] = useState<Record<string, unknown>[]>([]);
              const [loading, setLoading] = useState(false);
                const [msg, setMsg] = useState<string | null>(null);

                  async function load() {
                      setLoading(true);
                          setMsg(null);
                              try {
                                    const data = await fetchRecent(city);
                                          setRows(data.rows || []);
                                              } catch (e: unknown) {
                                                    const m = e instanceof Error ? e.message : String(e);
                                                          setMsg(`Load error: ${m}`);
                                                                setRows([]);
                                                                    } finally {
                                                                          setLoading(false);
                                                                              }
                                                                                }

                                                                                  useEffect(() => { load(); }, [city]);

                                                                                    async function handleCSV(scope: "weho" | "beverlyhills" | "combined") {
                                                                                        try {
                                                                                              const url = await exportCSV(scope);
                                                                                                    const a = document.createElement("a");
                                                                                                          a.href = url;
                                                                                                                a.download = `permitpulse_${scope}_${Date.now()}.csv`;
                                                                                                                      a.click();
                                                                                                                            URL.revokeObjectURL(url);
                                                                                                                                } catch (e: unknown) {
                                                                                                                                      setMsg(`CSV error: ${e instanceof Error ? e.message : String(e)}`);
                                                                                                                                          }
                                                                                                                                            }

                                                                                                                                              async function handleSubscribe(form: { email?: string; phone?: string; area?: string }) {
                                                                                                                                                  setMsg(null);
                                                                                                                                                      try {
                                                                                                                                                            const res = await subscribe(form);
                                                                                                                                                                  setMsg(res.ok ? "Subscribed! 🎉" : `Subscribe failed: ${res.error || "Unknown"}`);
                                                                                                                                                                      } catch (e: unknown) {
                                                                                                                                                                            setMsg(`Subscribe error: ${e instanceof Error ? e.message : String(e)}`);
                                                                                                                                                                                }
                                                                                                                                                                                  }

                                                                                                                                                                                    async function handleWaitlist(cityName: string, email: string) {
                                                                                                                                                                                        setMsg(null);
                                                                                                                                                                                            try {
                                                                                                                                                                                                  const res = await waitlist(cityName, email);
                                                                                                                                                                                                        setMsg(res.message);
                                                                                                                                                                                                            } catch (e: unknown) {
                                                                                                                                                                                                                  setMsg(`Waitlist error: ${e instanceof Error ? e.message : String(e)}`);
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                              <div style={{ maxWidth: 960, margin: "0 auto", padding: "24px" }}>
                                                                                                                                                                                                                                    <h1>PermitPulse</h1>
                                                                                                                                                                                                                                          <p style={{ marginTop: 4, color: "#666" }}>
                                                                                                                                                                                                                                                  Real‑time permits + alerts for LA neighborhoods. Connected to your Worker backend.
                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                              <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 16 }}>
                                                                                                                                                                                                                                                                      {(Object.keys(CITY_LABELS) as City[]).map((c) => (
                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                            key={c}
                                                                                                                                                                                                                                                                                                        onClick={() => setCity(c)}
                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                  padding: "8px 12px",
                                                                                                                                                                                                                                                                                                                                                borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                              border: "1px solid #ddd",
                                                                                                                                                                                                                                                                                                                                                                            background: c === city ? "#111" : "#fff",
                                                                                                                                                                                                                                                                                                                                                                                          color: c === city ? "#fff" : "#111",
                                                                                                                                                                                                                                                                                                                                                                                                        cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                          {CITY_LABELS[c]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginTop: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => handleCSV("combined")} style={{ marginRight: 8 }}>Download Combined CSV</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => handleCSV("weho")} style={{ marginRight: 8 }}>WEHO CSV</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => handleCSV("beverlyhills")}>Beverly Hills CSV</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading && <p style={{ marginTop: 16 }}>Loading…</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {msg && <p style={{ marginTop: 16, color: "#b00020" }}>{msg}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <RecentTable rows={rows} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 style={{ marginTop: 32 }}>Subscribe for Alerts</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <SubscribeForm onSubmit={handleSubscribe} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 style={{ marginTop: 24 }}>Waitlist a City</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onSubmit={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const fd = new FormData(e.currentTarget as HTMLFormElement);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const cityName = String(fd.get("city") || "");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const email = String(fd.get("email") || "");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          handleWaitlist(cityName, email);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (e.currentTarget as HTMLFormElement).reset();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input name="city" placeholder="City name" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input name="email" placeholder="email@you.com" type="email" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit">Join Waitlist</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }