// src/App.tsx
import { useEffect, useState } from "react";
import CityBlock from "./components/CityBlock";
import SubscribeForm from "./components/SubscribeForm";
import { api } from "./lib/api";

type Tab = "home" | "weho" | "bevhills" | "combined" | "admin";

export default function App() {
  const [tab, setTab] = useState<Tab>("home");
    const [health, setHealth] = useState<any>(null);

      useEffect(() => {
          api.health().then(setHealth).catch(() => {});
            }, []);

              return (
                  <div className="container">
                        <header>
                                <h1>PermitPulse</h1>
                                        <nav>
                                                  <a onClick={() => setTab("home")}>Home</a>
                                                            <a onClick={() => setTab("weho")}>WeHo</a>
                                                                      <a onClick={() => setTab("bevhills")}>Beverly Hills</a>
                                                                                <a onClick={() => setTab("combined")}>LA City + County</a>
                                                                                          <a onClick={() => setTab("admin")}>Admin</a>
                                                                                                  </nav>
                                                                                                        </header>

                                                                                                              {tab === "home" && (
                                                                                                                      <>
                                                                                                                                <div className="card">
                                                                                                                                            <h2>Real‑time permit radar for LA</h2>
                                                                                                                                                        <p>
                                                                                                                                                                      Fresh permits, simple alerts, and AI summaries for contractors, designers, and
                                                                                                                                                                                    homeowners. Try a city, or subscribe below.
                                                                                                                                                                                                </p>
                                                                                                                                                                                                            <ul>
                                                                                                                                                                                                                          <li>✅ West Hollywood open data (Socrata)</li>
                                                                                                                                                                                                                                        <li>✅ Beverly Hills CSV endpoint</li>
                                                                                                                                                                                                                                                      <li>✅ Combined LA City + County (where available)</li>
                                                                                                                                                                                                                                                                    <li>🟨 More cities coming—join the waitlist</li>
                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                            {health?.counts && (
                                                                                                                                                                                                                                                                                                          <pre className="health">{JSON.stringify(health.counts, null, 2)}</pre>
                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                          <SubscribeForm />
                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                              {tab === "weho" && <CityBlock city="weho" />}
                                                                                                                                                                                                                                                                                                                                                                    {tab === "bevhills" && <CityBlock city="beverlyhills" />}
                                                                                                                                                                                                                                                                                                                                                                          {tab === "combined" && <CityBlock city="combined" />}

                                                                                                                                                                                                                                                                                                                                                                                {tab === "admin" && (
                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                  <AdminLazy />
                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                      <footer>
                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Worker: {import.meta.env.VITE_WORKER_BASE || "(set VITE_WORKER_BASE)"}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="spacer" />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="https://getpermitpulse.com" target="_blank">GetPermitPulse.com</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                          function AdminLazy() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [Comp, setComp] = useState<null | any>(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  import("./pages/Admin").then((m) => setComp(() => m.default));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return Comp ? <Comp /> : <div className="card">Loading admin…</div>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }