// src/pages/Admin.tsx
import { useEffect, useMemo, useState } from "react";
import { supabaseClient } from "../lib/api";

export default function Admin() {
  const [authed, setAuthed] = useState(false);
    const [pass, setPass] = useState("");
      const [rows, setRows] = useState<any[]>([]);
        const [loading, setLoading] = useState(false);
          const [err, setErr] = useState<string | null>(null);

            const needsSupabase = useMemo(() => {
                return !(import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY);
                  }, []);

                    async function load() {
                        setErr(null);
                            setLoading(true);
                                try {
                                      const sb = await supabaseClient();
                                            if (!sb) throw new Error("Supabase not configured");
                                                  const { data, error } = await sb
                                                          .from("subscribers")
                                                                  .select("*")
                                                                          .order("created_at", { ascending: false })
                                                                                  .limit(500);
                                                                                        if (error) throw error;
                                                                                              setRows(data || []);
                                                                                                  } catch (e: any) {
                                                                                                        setErr(e.message || "Failed to load");
                                                                                                            } finally {
                                                                                                                  setLoading(false);
                                                                                                                      }
                                                                                                                        }

                                                                                                                          function csv() {
                                                                                                                              const cols = ["email", "phone", "area", "created_at"];
                                                                                                                                  const lines = [cols.join(",")].concat(
                                                                                                                                        rows.map((r) => cols.map((c) => safeCsv(r[c])).join(","))
                                                                                                                                            );
                                                                                                                                                download("subscribers.csv", lines.join("\n"));
                                                                                                                                                  }

                                                                                                                                                    function mailto() {
                                                                                                                                                        const emails = rows.map((r) => r.email).filter(Boolean);
                                                                                                                                                            const batch = emails.slice(0, 50).join(",");
                                                                                                                                                                window.location.href = `mailto:?bcc=${encodeURIComponent(batch)}&subject=${encodeURIComponent(
                                                                                                                                                                      "PermitPulse update"
                                                                                                                                                                          )}`;
                                                                                                                                                                            }

                                                                                                                                                                              if (!authed) {
                                                                                                                                                                                  return (
                                                                                                                                                                                        <div className="card">
                                                                                                                                                                                                <h3>Admin login</h3>
                                                                                                                                                                                                        <p className="muted">Enter the admin passphrase.</p>
                                                                                                                                                                                                                <input
                                                                                                                                                                                                                          type="password"
                                                                                                                                                                                                                                    placeholder="passphrase"
                                                                                                                                                                                                                                              value={pass}
                                                                                                                                                                                                                                                        onChange={(e) => setPass(e.target.value)}
                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                  onClick={() => {
                                                                                                                                                                                                                                                                                              if (pass === import.meta.env.VITE_ADMIN_PASS) setAuthed(true);
                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                          Enter
                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                    <div className="card">
                                                                                                                                                                                                                                                                                                                                                          <h3>Subscribers</h3>
                                                                                                                                                                                                                                                                                                                                                                {needsSupabase ? (
                                                                                                                                                                                                                                                                                                                                                                        <p className="error">
                                                                                                                                                                                                                                                                                                                                                                                  Set <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_ANON_KEY</code> to use this
                                                                                                                                                                                                                                                                                                                                                                                            view.
                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={load} disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? "Loading…" : "Refresh"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="spacer" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={csv} disabled={!rows.length}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Export CSV
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={mailto} disabled={!rows.length}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Mailto (first 50 BCC)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="muted">{rows.length} subscriber(s)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="table-wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <th>email</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <th>phone</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>area</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th>created_at</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {rows.map((r) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr key={r.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td>{r.email}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>{r.phone}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{r.area}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>{new Date(r.created_at).toLocaleString()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function safeCsv(v: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const s = v == null ? "" : String(v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return `"${s.replace(/"/g, '""')}"`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function download(filename: string, text: string) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const blob = new Blob([text], { type: "text/csv;charset=utf-8" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const url = URL.createObjectURL(blob);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const a = document.createElement("a");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              a.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                a.download = filename;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  a.click();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    URL.revokeObjectURL(url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }