export const JURISDICTIONS = [
	{
		id: 'la_city',
		name: 'Los Angeles',
		placeholder: true,
		provider: {
			type: 'socrata',
			domain: 'data.lacity.org',
			dataset: 'pi9x-tg5x',
			fields: {
				id: 'permit_nbr',
				address: 'primary_address',
				status: null,
				type: 'permit_type',
				subtype: 'permit_sub_type',
				filed_at: 'issue_date',
				issued_at: null,
				valuation: 'valuation',
				description: 'work_desc',
			},
			searchFields: ['primary_address', 'permit_nbr', 'work_desc', 'permit_type', 'permit_sub_type'],
		},
	},
	{
		id: 'la_county',
		name: 'LA County (EPIC-LA Case History)',
		provider: {
			type: 'arcgis',
			layerBaseUrl: 'https://services.arcgis.com/RmCqQtiZLDCtblq/arcgis/rest/services/LA_County_Permitting_EPIC_LA_Case_History/FeatureServer/0',
			orderByFields: 'STATUS_DATE DESC',
			fields: {
				id: 'CASE_NUMBER',
				address: 'SITUS_ADDRESS',
				status: 'CASE_STATUS',
				type: 'CASE_TYPE',
				subtype: 'CASE_SUBTYPE',
				filed_at: 'STATUS_DATE',
				issued_at: 'ISSUED_DATE',
				valuation: 'VALUATION',
				description: 'APPLICANT',
				alt_address: 'SITUS_ADDRESS_2',
				apn: 'APN',
				city: 'CITY',
				zip: 'ZIP',
			},
			searchFields: ['CASE_NUMBER', 'SITUS_ADDRESS', 'SITUS_ADDRESS_2', 'CASE_STATUS', 'CASE_TYPE', 'CASE_SUBTYPE', 'APPLICANT', 'APN', 'CITY', 'ZIP'],
		},
	},
];
