export const JURISDICTIONS = [
  {
    id: "la_city",
    name: "Los Angeles",
    placeholder: true,
    enabled: true,
    provider: {
      type: "socrata",
      domain: "data.lacity.org",
      dataset: "pi9x-tg5x",
      fields: {
        id: "permit_nbr",
        address: "primary_address",
        status: null,
        type: "permit_type",
        subtype: "permit_sub_type",
        filed_at: "issue_date",
        issued_at: null,
        valuation: "valuation",
        description: "work_desc",
      },
      searchFields: ["primary_address", "permit_nbr", "work_desc", "permit_type", "permit_sub_type"],
    },
  },

  {
    id: "la_county",
    name: "LA County (EPIC-LA Case History)",
    placeholder: true,
    enabled: true,
    provider: null,
    portalUrl: "https://epicla.lacounty.gov/",
    portalNotes: "No direct data feed yet. Search via official LA County permit portal.",
  },

  {
    id: "alameda",
    name: "Alameda",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://www.alamedaca.gov/aca",
    portalNotes: "No direct data feed yet. Use the official Accela Citizen Access portal.",
  },

  {
    id: "belmont",
    name: "Belmont",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "eTRAKiT",
    portalUrl: "https://www.belmont.gov/departments/community-development/building-department/search-permits-projects-parcels",
    portalNotes: "No direct data feed yet. Public search is available via the official eTRAKiT page.",
  },

  {
    id: "beverly_hills",
    name: "Beverly Hills",
    placeholder: true,
    enabled: true,
    provider: {
      type: "arcgis",
      layerBaseUrl: "https://services5.arcgis.com/7CXE3aevo18HlHBC/arcgis/rest/services/Permit_Issued_All/FeatureServer/0",
      orderByFields: "OBJECTID DESC",
      fields: {
        id: "PERMIT_NUMBER",
        address: "ADDRESS",
        status: null,
        type: "PERMIT_TYPE",
        subtype: null,
        filed_at: null,
        issued_at: null,
        valuation: "VALUATION",
        description: "PERMIT_DESCRIPTION",
        apn: "Derived_APN",
      },
      searchFields: [
        "PERMIT_NUMBER","ADDRESS","PERMIT_TYPE","PERMIT_DESCRIPTION","VALUATION","ISSUED_MONTH","ISSUED_YEAR","Derived_APN"
      ],
    },
  },

  {
    id: "culver_city",
    name: "Culver City",
    placeholder: true,
    enabled: true,
    provider: {
      type: "arcgis",
      layerBaseUrl: "https://services2.arcgis.com/LNAhiRpezPbHTIUO/arcgis/rest/services/Accela_Building_Safety_Permits/FeatureServer/0",
      orderByFields: "USER_StatusDate DESC",
      fields: {
        id: "USER_PermitNumber",
        address: "USER_FullAddress",
        status: "USER_RecordStatus",
        type: "USER_PermitType",
        subtype: "USER_PermitSubType",
        filed_at: "USER_DateOpened",
        issued_at: "USER_StatusDate",
        valuation: null,
        description: "USER_DescriptionOfWork",
        alt_address: "USER_StreetAddress",
        city: "USER_City",
        zip: "USER_ZipCode",
      },
      searchFields: [
        "USER_PermitNumber","USER_FullAddress","USER_DescriptionOfWork","USER_PermitType","USER_RecordStatus","USER_PermitGroup","USER_PermitSubType","USER_StreetAddress","USER_StreetName","USER_City","USER_ZipCode"
      ],
    },
  },

  {
    id: "contra_costa_county",
    name: "Contra Costa County",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://www.contracosta.ca.gov/8012/ePermit-Center",
    portalNotes: "No direct data feed yet. Use the official ePermits Center.",
  },

  {
    id: "lodi",
    name: "Lodi",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "eTRAKiT",
    portalUrl: "https://www.lodi.gov/1239/eTRAKiT---Online-Permitting",
    portalNotes: "No direct data feed yet. Use the official eTRAKiT online permitting page.",
  },

  {
    id: "ontario",
    name: "Ontario",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://aca-prod.accela.com/ont/Default.aspx",
    portalNotes: "No direct data feed yet. Use the official Citizen Access portal.",
  },

  {
    id: "riverside",
    name: "Riverside",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "POSSE",
    portalUrl: "https://riversideca.gov/cedd/planning/public-permit-portal",
    portalNotes: "No direct data feed yet. Use the official public permit portal.",
  },

  {
    id: "sacramento",
    name: "Sacramento",
    state: "CA",
    placeholder: true,
    enabled: true,
    platform: "Open Data (ArcGIS)",
    portalUrl: "https://www.cityofsacramento.gov/community-development/building/permit-services",
    portalNotes: "Official Sacramento permit services page with access to the public permit portal. PermitPulse also queries the city's public ArcGIS permit feed.",
    provider: {
      type: "arcgis",
      layerBaseUrl: "https://services5.arcgis.com/54falWtcpty3V47Z/arcgis/rest/services/BldgPermitIssued_CurrentYear/FeatureServer/0",
      orderByFields: "OBJECTID DESC",
      fields: {
        id: "Application",
        address: "Address",
        status: "Current_Status",
        type: "Type",
        subtype: "Sub_Type",
        filed_at: "Status_Date",
        issued_at: "Status_Date",
        valuation: "Valuation",
        description: "Work_Desc",
        alt_address: "Site_Location",
        apn: "Parcel_No",
        zip: "ZIP",
      },
      searchFields: [
        "Application","Address","Work_Desc","Site_Location","Current_Status","Type","Sub_Type","Parcel_No","ZIP"
      ],
    },
  },

  {
    id: "sacramento_county",
    name: "Sacramento County",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://actonline.saccounty.gov/citizenaccess/sacco_help.aspx",
    portalNotes: "No direct data feed yet. Use the official Accela Citizen Access portal.",
  },

  {
    id: "san_bernardino_county",
    name: "San Bernardino County",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "EZOP",
    portalUrl: "https://wp.sbcounty.gov/ezop/",
    portalNotes: "No direct data feed yet. Use the official EZOP portal.",
  },

  {
    id: "san_diego_county",
    name: "San Diego County",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: {
      type: "socrata",
      domain: "data.sandiegocounty.gov",
      dataset: "dyzh-7eat",
      fields: {
        id: "record_id",
        address: "full_address",
        status: "record_status",
        type: "record_type",
        subtype: "record_category",
        filed_at: "open_date",
        issued_at: "issued_date",
        valuation: "valuation",
        description: "use",
      },
      searchFields: [
        "record_id","full_address","street_address","city","zip_code","parcel_number","record_status","record_type","record_subtype","record_category","use","contractor_name"
      ],
    },
    platform: "Accela",
    portalUrl: "https://publicservices.sandiegocounty.gov/CitizenAccess/Default.aspx",
    portalNotes: "Official Accela Citizen Access portal fallback for record lookup.",
  },

  {
    id: "san_jose",
    name: "San Jose",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: {
      type: "ckan",
      domain: "data.sanjoseca.gov",
      resourceId: "761b7ae8-3be1-4ad6-923d-c7af6404a904",
      sort: "ISSUEDATE desc",
      fields: {
        id: "FOLDERNUMBER",
        address: null,
        status: "Status",
        type: "FOLDERDESC",
        subtype: "SUBTYPEDESCRIPTION",
        filed_at: "ISSUEDATE",
        issued_at: "ISSUEDATE",
        valuation: "PERMITVALUATION",
        description: "WORKDESCRIPTION",
      },
    },
  },

  {
    id: "san_francisco",
    name: "San Francisco",
    placeholder: true,
    enabled: true,
    provider: {
      type: "socrata",
      domain: "data.sfgov.org",
      dataset: "i98e-djp9",
      fields: {
        id: "permit_number",
        address: "street_name",
        status: "status",
        type: "permit_type",
        subtype: "permit_type_definition",
        filed_at: "filed_date",
        issued_at: "issued_date",
        valuation: "estimated_cost",
        description: "description",
      },
      searchFields: ["permit_number", "description", "status", "permit_type", "permit_type_definition", "street_name"],
    },
  },

  {
    id: "santa_clara_county",
    name: "Santa Clara County",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://plandev.santaclaracounty.gov/permits",
    portalNotes: "No direct data feed yet. Use the official public permit portal.",
  },

  {
    id: "long_beach",
    name: "Long Beach",
    placeholder: true,
    enabled: false,
    reason: "source not wired yet",
    provider: {
      type: "socrata",
      domain: "data.longbeach.gov",
      dataset: "y3ad-yhi1",
      fields: {
        id: "permit_number",
        address: "address",
        status: "status",
        type: null,
        subtype: null,
        filed_at: "file_date",
        issued_at: null,
        valuation: null,
        description: "description",
      },
      searchFields: ["permit_number", "address", "status", "description"],
    },
  },

  {
    id: "santa_monica",
    name: "Santa Monica",
    placeholder: true,
    enabled: true,
    searchFields: ["permit_number", "address", "description", "status", "permit_type", "sub_type"],
    provider: {
      type: "ckan",
      domain: "data.santamonica.gov",
      resourceId: "d6867c7d-89bc-4975-be35-4d2673a4764b",
      sort: "date_entered desc",
      fields: {
        id: "permit_number",
        address: "address",
        status: "status",
        type: "permit_type",
        subtype: "sub_type",
        filed_at: "date_entered",
        issued_at: "date_issued",
        valuation: "valuation",
        description: "description",
      },
    },
  },

  {
    id: "solana_beach",
    name: "Solana Beach",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "eTRAKiT",
    portalUrl: "https://www.cityofsolanabeach.org/en/building-services",
    portalNotes: "No direct data feed yet. Use the official building services page for eTRAKiT access details.",
  },

  {
    id: "albuquerque",
    name: "Albuquerque",
    state: "NM",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "ABQ-PLAN",
    portalUrl: "https://www.cabq.gov/planning/building-safety-division/permits",
    portalNotes: "No direct data feed yet. Use the official permit page to route into ABQ-PLAN for applications and status.",
  },

  {
    id: "atlanta",
    name: "Atlanta",
    state: "GA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://www.atlantaga.gov/government/departments/city-planning/zoning-development-permitting-services/online-permitting",
    portalNotes: "No direct data feed yet. Use the official online permitting page to launch the city's Accela workflow.",
  },

  {
    id: "baltimore",
    name: "Baltimore",
    state: "MD",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "E-Permits",
    portalUrl: "https://beta.baltimorecity.gov.ifsight.net/permits-and-licensing/building",
    portalNotes: "No direct data feed yet. Use the official Baltimore e-permits building portal for permit routing and status.",
  },

  {
    id: "boston",
    name: "Boston",
    state: "MA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Boston Permit Finder",
    portalUrl: "https://permitfinder.boston.gov/",
    portalNotes: "No direct data feed yet. Use the official Boston Permit Finder to look up active permit status by permit number.",
  },

  {
    id: "colorado_springs",
    name: "Colorado Springs",
    state: "CO",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://aca-prod.accela.com/COSPRINGS/Default.aspx",
    portalNotes: "No direct data feed yet. Use the official City of Colorado Springs Citizen Access portal to search applications and permit status.",
  },

  {
    id: "detroit",
    name: "Detroit",
    state: "MI",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela / eLAPS",
    portalUrl: "https://detroitmi.gov/node/40371",
    portalNotes: "No direct data feed yet. Use the official Detroit Accela / eLAPS launch page to route into online permits and licensing.",
  },

  {
    id: "el_paso",
    name: "El Paso",
    state: "TX",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://aca-prod.accela.com/ELPASO/Default.aspx",
    portalNotes: "No direct data feed yet. Use the official City of El Paso Citizen Access portal to search permit and license applications.",
  },

  {
    id: "fresno",
    name: "Fresno",
    state: "CA",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://aca-prod.accela.com/FRESNO/Default.aspx",
    portalNotes: "No direct data feed yet. Use the official Fresno Accela Citizen Access portal for planning and building records.",
  },

  {
    id: "kansas_city",
    name: "Kansas City",
    state: "MO",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "CompassKC",
    portalUrl: "https://compasskc.kcmo.org/",
    portalNotes: "No direct data feed yet. Use the official CompassKC system for permits, plans, and inspections.",
  },

  {
    id: "las_vegas",
    name: "Las Vegas",
    state: "NV",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Citizen Portal",
    portalUrl: "https://www.lasvegasnevada.gov/kiosk/dsc/English",
    portalNotes: "No direct data feed yet. Use the official Las Vegas citizen portal for permit applications, payments, and status.",
  },

  {
    id: "louisville",
    name: "Louisville",
    state: "KY",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Online Permitting Portal",
    portalUrl: "https://louisvilleky.gov/government/construction-review/online-permitting-portal",
    portalNotes: "No direct data feed yet. Use the official Louisville online permitting portal page for permit search and application routing.",
  },

  {
    id: "memphis",
    name: "Memphis",
    state: "TN",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Permit Administration Website",
    portalUrl: "https://permitspayments.memphistn.gov/",
    portalNotes: "No direct data feed yet. Use the official Memphis permit administration portal for permit registration and payment.",
  },

  {
    id: "mesa",
    name: "Mesa",
    state: "AZ",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "DIMES",
    portalUrl: "https://www.mesaaz.gov/Business-Development/Development-Services/Building-Permit-Plan-Review",
    portalNotes: "No direct data feed yet. Use the official Mesa development services page to route into the DIMES ePermit workflow.",
  },

  {
    id: "milwaukee",
    name: "Milwaukee",
    state: "WI",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "LMS Land Management System",
    portalUrl: "https://city.milwaukee.gov/DNS/permits",
    portalNotes: "No direct data feed yet. Use the official DNS permits page to access Milwaukee's LMS permit system.",
  },

  {
    id: "nashville",
    name: "Nashville",
    state: "TN",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "E-Permits",
    portalUrl: "https://epermits.nashville.gov/",
    portalNotes: "No direct data feed yet. Use the official Nashville ePermits public inquiry system for permit lookup.",
  },

  {
    id: "oklahoma_city",
    name: "Oklahoma City",
    state: "OK",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Accela",
    portalUrl: "https://access.okc.gov/aca/Default.aspx",
    portalNotes: "No direct data feed yet. Use the official Oklahoma City Citizen Portal to search permit records and applications.",
  },

  {
    id: "omaha",
    name: "Omaha",
    state: "NE",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Omaha ONEBiz",
    portalUrl: "https://onebiz.cityofomaha.org/comply-with-regulatory-permitting-page",
    portalNotes: "No direct data feed yet. Use Omaha's official ONEBiz regulatory permitting workflow as the current online routing page; public planning and building record search remains fragmented across city systems.",
  },

  {
    id: "portland",
    name: "Portland",
    state: "OR",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Development Hub PDX",
    portalUrl: "https://www.portland.gov/ppd/get-permit/check-permit-status",
    portalNotes: "No direct data feed yet. Use the official Portland permit status page to route into Development Hub PDX for applications and status.",
  },

  {
    id: "tucson",
    name: "Tucson",
    state: "AZ",
    placeholder: true,
    enabled: true,
    provider: null,
    platform: "Tucson Development Center Online",
    portalUrl: "https://www.tucsonaz.gov/Departments/Planning-Development-Services/Permits",
    portalNotes: "No direct data feed yet. Use the official Tucson permits page to launch Tucson Development Center Online.",
  },
];
