import { useEffect, useMemo, useState } from "react";
import CityButtons from "../components/CityButtons";
import CityStats from "../components/CityStats";
import PermitTrend from "../components/PermitTrend";
import PermitTable from "../components/PermitTable";
import HealthCard from "../components/HealthCard";
// If you don’t have WaitlistModal wired yet, you can comment this next line out
import WaitlistModal from "../components/WaitlistModal";

type PermitRow = {
  permit_number?: string;
    status?: string;
      issue_date?: string;
        address?: string;
          work_description?: string;
            city?: string;
            };

            const API_BASE =
              (import.meta as any).env?.VITE_API_BASE?.replace(/\/+$/, "") ||
                "https://api.getpermitpulse.com";

                const ENDPOINT: Record<string, string> = {
                  weho: "weho/recent",
                    beverlyhills: "beverlyhills/recent",
                      altadena: "altadena/recent",
                        palisades: "palisades/recent",
                          combined: "combined/recent",
                            sandiego: "sandiego/recent",
                              sacramento: "sacramento/recent",
                              };

                              async function fetchRecent(city: string): Promise<PermitRow[]> {
                                const path = ENDPOINT[city] ?? ENDPOINT.weho;
                                  const resp = await fetch(`${API_BASE}/${path}`, { headers: { Accept: "application/json" } });
                                    if (!resp.ok) throw new Error(`${resp.status}`);
                                      const data = await resp.json();
                                        return Array.isArray(data?.permits) ? data.permits : [];
                                        }

                                        export default function Home() {
                                          const [city, setCity] = useState<keyof typeof ENDPOINT>("weho");
                                            const [rows, setRows] = useState<PermitRow[]>([]);
                                              const [loading, setLoading] = useState(false);
                                                const [err, setErr] = useState<string | null>(null);

                                                  // simple UI state
                                                    const [waitlistOpen, setWaitlistOpen] = useState(false);
                                                      const [q, setQ] = useState("");
                                                        const [sortKey, setSortKey] = useState<keyof PermitRow | "issue_date">("issue_date");
                                                          const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");

                                                            // fetch whenever city changes
                                                              useEffect(() => {
                                                                  let cancelled = false;
                                                                      setLoading(true);
                                                                          setErr(null);
                                                                              fetchRecent(city)
                                                                                    .then((r) => !cancelled && setRows(r))
                                                                                          .catch((e) => !cancelled && setErr(e?.message ?? "Failed to fetch"))
                                                                                                .finally(() => !cancelled && setLoading(false));
                                                                                                    return () => {
                                                                                                          cancelled = true;
                                                                                                              };
                                                                                                                }, [city]);

                                                                                                                  // filtering + sorting kept tiny and fast on the client
                                                                                                                    const viewRows = useMemo(() => {
                                                                                                                        let r = rows;
                                                                                                                            if (q) {
                                                                                                                                  const n = q.toLowerCase();
                                                                                                                                        r = r.filter(
                                                                                                                                                (x) =>
                                                                                                                                                          (x.address || "").toLowerCase().includes(n) ||
                                                                                                                                                                    (x.permit_number || "").toLowerCase().includes(n) ||
                                                                                                                                                                              (x.status || "").toLowerCase().includes(n) ||
                                                                                                                                                                                        (x.work_description || "").toLowerCase().includes(n)
                                                                                                                                                                                              );
                                                                                                                                                                                                  }
                                                                                                                                                                                                      const dir = sortDir === "asc" ? 1 : -1;
                                                                                                                                                                                                          return [...r].sort((a, b) => {
                                                                                                                                                                                                                const av = (a[sortKey] ?? "") as string;
                                                                                                                                                                                                                      const bv = (b[sortKey] ?? "") as string;
                                                                                                                                                                                                                            // special-case dates
                                                                                                                                                                                                                                  if (sortKey === "issue_date") {
                                                                                                                                                                                                                                          return (new Date(av).getTime() - new Date(bv).getTime()) * dir;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                      return av.localeCompare(bv) * dir;
                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                            }, [rows, q, sortKey, sortDir]);

                                                                                                                                                                                                                                                              const handleSort = (key: keyof PermitRow | "issue_date") => {
                                                                                                                                                                                                                                                                  setSortKey(key);
                                                                                                                                                                                                                                                                      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                              <div className="p-4 md:p-6 max-w-6xl mx-auto">
                                                                                                                                                                                                                                                                                    <CityButtons
                                                                                                                                                                                                                                                                                            value={city}
                                                                                                                                                                                                                                                                                                    onChange={(c) => setCity(c as any)}
                                                                                                                                                                                                                                                                                                            // Make sure your CityButtons set includes: weho, beverlyhills, altadena, palisades, combined
                                                                                                                                                                                                                                                                                                                    // (and you can add sandiego / sacramento when ready)
                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                <div className="mt-4 grid grid-cols-1 lg:grid-cols-3 gap-4">
                                                                                                                                                                                                                                                                                                                                        <div className="lg:col-span-2">
                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-2xl font-semibold mb-2 capitalize">
                                                                                                                                                                                                                                                                                                                                                              {city === "weho"
                                                                                                                                                                                                                                                                                                                                                                            ? "West Hollywood"
                                                                                                                                                                                                                                                                                                                                                                                          : city === "beverlyhills"
                                                                                                                                                                                                                                                                                                                                                                                                        ? "Beverly Hills"
                                                                                                                                                                                                                                                                                                                                                                                                                      : city === "altadena"
                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "Altadena"
                                                                                                                                                                                                                                                                                                                                                                                                                                                  : city === "palisades"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? "Pacific Palisades"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : city === "combined"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "All Cities"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          : city === "sandiego"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? "San Diego"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : city === "sacramento"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? "Sacramento"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-2 text-sm text-slate-300 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={q}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setQ(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Search address, status, permit…"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-md bg-slate-800 border border-slate-700 px-3 py-2 outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <CityStats rows={rows} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <PermitTrend rows={rows} />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <PermitTable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rows={viewRows}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      loading={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  error={err}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              showCity={city === "combined"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sortKey={sortKey}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sortDir={sortDir}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onSort={handleSort}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <HealthCard />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => setWaitlistOpen(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white py-2 font-medium"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Join Early Access
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {waitlistOpen && <WaitlistModal onClose={() => setWaitlistOpen(false)} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }