import React, { useEffect, useState } from "react";

type Props = { onClose?: () => void };

type Stats = { ok: boolean; total: number; joined: number; remaining: number };

export default function WaitlistModal({ onClose }: Props) {
  const [stats, setStats] = useState<Stats | null>(null);
    const [email, setEmail] = useState("");
      const [busy, setBusy] = useState(false);
        const [done, setDone] = useState(false);
          const [err, setErr] = useState<string | null>(null);

            useEffect(() => {
                let cancelled = false;
                    (async () => {
                          try {
                                  const r = await fetch("https://api.getpermitpulse.com/waitlist/stats", {
                                            headers: { Accept: "application/json" },
                                                    });
                                                            const j = (await r.json()) as Stats;
                                                                    if (!cancelled && j?.ok) setStats(j);
                                                                          } catch {
                                                                                  if (!cancelled) {
                                                                                            // fallback numbers
                                                                                                      setStats({ ok: true, total: 100, joined: 28, remaining: 72 });
                                                                                                              }
                                                                                                                    }
                                                                                                                        })();
                                                                                                                            return () => {
                                                                                                                                  cancelled = true;
                                                                                                                                      };
                                                                                                                                        }, []);

                                                                                                                                          async function submit(e: React.FormEvent) {
                                                                                                                                              e.preventDefault();
                                                                                                                                                  setErr(null);
                                                                                                                                                      if (!email) {
                                                                                                                                                            setErr("Please enter an email");
                                                                                                                                                                  return;
                                                                                                                                                                      }
                                                                                                                                                                          setBusy(true);
                                                                                                                                                                              try {
                                                                                                                                                                                    // use your existing subscribe endpoint
                                                                                                                                                                                          const r = await fetch("/subscribe", {
                                                                                                                                                                                                  method: "POST",
                                                                                                                                                                                                          headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                  body: JSON.stringify({ email }),
                                                                                                                                                                                                                        });
                                                                                                                                                                                                                              if (!r.ok) throw new Error(`HTTP ${r.status}`);
                                                                                                                                                                                                                                    setDone(true);
                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                              setErr("Something went wrong. Please try again.");
                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                        setBusy(false);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                const remaining = stats?.remaining ?? 72;
                                                                                                                                                                                                                                                                  const total = stats?.total ?? 100;

                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70">
                                                                                                                                                                                                                                                                              <div className="w-[92%] max-w-md rounded-xl border border-white/10 bg-[#0b1220] p-5 shadow-xl">
                                                                                                                                                                                                                                                                                      <div className="mb-3 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                <div className="text-white text-lg font-semibold">Early Access</div>
                                                                                                                                                                                                                                                                                                          <span className="rounded-full bg-emerald-500/15 text-emerald-300 text-xs px-2 py-1">
                                                                                                                                                                                                                                                                                                                      {total} spots • {remaining} left
                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                <p className="text-white/80 text-sm mb-4">
                                                                                                                                                                                                                                                                                                                                                          Get permits before the crowd. Join the early access list and lock in
                                                                                                                                                                                                                                                                                                                                                                    founder pricing forever.
                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                    {done ? (
                                                                                                                                                                                                                                                                                                                                                                                              <div className="rounded-md bg-emerald-600/15 text-emerald-300 p-3 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                          You’re on the list! We’ll email you as new cities go live.
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <form onSubmit={submit} className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setEmail(e.currentTarget.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full rounded-md bg-black/30 border border-white/10 px-3 py-2 text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-white/20"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="your@email.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {err && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-rose-300/90 bg-rose-500/10 border border-rose-500/20 rounded-md px-3 py-2 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {err}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={busy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full rounded-md bg-white/90 text-black font-medium py-2 hover:bg-white transition disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {busy ? "Joining…" : "Join the Waitlist"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-4 flex items-center justify-between text-xs text-white/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Privacy-first • 1-click unsubscribe</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {onClose && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={onClose}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-white/60 hover:text-white/90 underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Close
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }