import { useEffect, useState, type FormEvent } from "react";
import { getReviewerWorkspace, saveActionKit, saveReviewerObject } from "../api/reviewer";
import type { EvidenceItemDto, TimelineEntryDto } from "../types/evidence-timeline";
import type { ReviewerAction, ReviewerActionKit, ReviewerFinding, ReviewerNote, ReviewerQuestion, ReviewerWorkspace } from "../../shared/reviewer/types";

type Editable<T extends {id:string;case_id:string;version:number;created_at:string;updated_at:string}> = {
  [K in keyof Omit<T,"id"|"case_id"|"version"|"created_at"|"updated_at">]: Omit<T,"id"|"case_id"|"version"|"created_at"|"updated_at">[K] extends string ? string : Omit<T,"id"|"case_id"|"version"|"created_at"|"updated_at">[K]
} & Partial<Pick<T,"id"|"version">>;
const emptyFinding: Editable<ReviewerFinding> = { title:"", finding_type:"risk", severity:"medium", summary:"", evidence_ids:[], timeline_ids:[], confidence:"medium", recommended_resolution:"", internal_notes:"", approved:false };
const emptyQuestion: Editable<ReviewerQuestion> = { question:"", why_it_matters:"", evidence_requested:"", assigned_reviewer:"", status:"open", publishable:true };
const emptyAction: Editable<ReviewerAction> = { priority:"medium", description:"", evidence_ids:[], estimated_impact:"", responsible_party:"", due_date:null, approved:false };
const emptyNote: Editable<ReviewerNote> = {commentary:"",publishable:false};
const emptyKit:Editable<ReviewerActionKit>={current_position:"",confirmed_record:"",unconfirmed_record:"",primary_blocker:"",why_appropriate:"",evidence_readiness:"",review_readiness:"",email_subject:"",recipient_role:"",message_body:"",call_checklist:[],requested_confirmations:[],documents_ready:[],escalation_trigger:"",follow_up_date:null,evidence_ids:[],timeline_ids:[],internal_note:"",approved:false};

export function ReviewerWorkspacePanel({caseId,evidence,timeline}:{caseId:string;evidence:EvidenceItemDto[];timeline:TimelineEntryDto[]}) {
  const [workspace,setWorkspace] = useState<ReviewerWorkspace|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const [finding,setFinding]=useState<Editable<ReviewerFinding>>(emptyFinding); const [question,setQuestion]=useState<Editable<ReviewerQuestion>>(emptyQuestion); const [action,setAction]=useState<Editable<ReviewerAction>>(emptyAction); const [note,setNote]=useState<Editable<ReviewerNote>>(emptyNote);
  const [kit,setKit]=useState<Editable<ReviewerActionKit>>(emptyKit);
  useEffect(()=>{ let active=true; void getReviewerWorkspace(caseId).then((v)=>{if(active){setWorkspace(v);setKit(v.action_kit?{...v.action_kit}:emptyKit)}}).catch(()=>{if(active)setError("Reviewer workspace could not be loaded.")}); return()=>{active=false}; },[caseId]);
  async function save(path:string,value:unknown,reset:()=>void,id?:string){ setSaving(true);setError("");try{setWorkspace(await saveReviewerObject(caseId,path,value,id));reset();}catch(e){setError(e instanceof Error?e.message:"Reviewer edit could not be saved.");}finally{setSaving(false);} }
  function submit(event:FormEvent,path:string,value:unknown,reset:()=>void,id?:string){event.preventDefault();void save(path,value,reset,id);}
  const toggle=(items:string[],id:string)=>items.includes(id)?items.filter((x)=>x!==id):[...items,id];
  const splitLines=(value:string)=>value.split(/\n/).map(x=>x.trim()).filter(Boolean);
  if (!workspace) return <section className="reviewer-workspace"><p>{error||"Loading reviewer workspace…"}</p></section>;
  return <section className="reviewer-workspace" aria-labelledby="reviewer-workspace-title">
    <header className="cockpit-section-heading"><p className="eyebrow">Editorial workspace</p><h2 id="reviewer-workspace-title">Reviewer</h2><p>Shape the client narrative from structured case records. Internal commentary stays out of packet exports.</p></header>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <section className="reviewer-block"><h3>Decision Brief &amp; Action Kit</h3><p>Reviewer-authored client language. Approval controls export; the internal note always stays private.</p><form className="reviewer-inline-form" onSubmit={e=>{e.preventDefault();setSaving(true);setError("");void saveActionKit(caseId,kit).then(v=>{setWorkspace(v);if(v.action_kit)setKit({...v.action_kit});}).catch(err=>setError(err instanceof Error?err.message:"Action Kit could not be saved.")).finally(()=>setSaving(false));}}>
      <textarea required aria-label="Current position" placeholder="Current position" value={kit.current_position} onChange={e=>setKit({...kit,current_position:e.target.value})}/><textarea required aria-label="What the record confirms" placeholder="What the record confirms" value={kit.confirmed_record} onChange={e=>setKit({...kit,confirmed_record:e.target.value})}/><textarea required aria-label="What the record does not confirm" placeholder="What the record does not confirm" value={kit.unconfirmed_record} onChange={e=>setKit({...kit,unconfirmed_record:e.target.value})}/><textarea required aria-label="Primary blocker" placeholder="Primary blocker" value={kit.primary_blocker} onChange={e=>setKit({...kit,primary_blocker:e.target.value})}/><textarea required aria-label="Why this move is appropriate" placeholder="Why this move is appropriate" value={kit.why_appropriate} onChange={e=>setKit({...kit,why_appropriate:e.target.value})}/><input required placeholder="Evidence readiness" value={kit.evidence_readiness} onChange={e=>setKit({...kit,evidence_readiness:e.target.value})}/><input required placeholder="Review readiness" value={kit.review_readiness} onChange={e=>setKit({...kit,review_readiness:e.target.value})}/>
      <input required aria-label="Agency follow-up subject" placeholder="Agency follow-up subject" value={kit.email_subject} onChange={e=>setKit({...kit,email_subject:e.target.value})}/><input required aria-label="Recipient or agency role" placeholder="Recipient or agency role" value={kit.recipient_role} onChange={e=>setKit({...kit,recipient_role:e.target.value})}/><textarea required aria-label="Agency follow-up message" placeholder="Short agency follow-up message" value={kit.message_body} onChange={e=>setKit({...kit,message_body:e.target.value})}/><textarea required aria-label="Requested confirmations" placeholder="Requested confirmations — one per line" value={kit.requested_confirmations.join("\n")} onChange={e=>setKit({...kit,requested_confirmations:splitLines(e.target.value)})}/><textarea required aria-label="Call checklist" placeholder="Call checklist — one per line" value={kit.call_checklist.join("\n")} onChange={e=>setKit({...kit,call_checklist:splitLines(e.target.value)})}/><textarea aria-label="Documents to have ready" placeholder="Documents to have ready — one per line" value={kit.documents_ready.join("\n")} onChange={e=>setKit({...kit,documents_ready:splitLines(e.target.value)})}/><textarea required aria-label="Escalation trigger" placeholder="Trigger for escalation" value={kit.escalation_trigger} onChange={e=>setKit({...kit,escalation_trigger:e.target.value})}/><input type="date" aria-label="Follow-up review date" value={kit.follow_up_date??""} onChange={e=>setKit({...kit,follow_up_date:e.target.value||null})}/>
      <div className="reviewer-reference-grid"><fieldset><legend>Referenced evidence</legend>{evidence.map(x=><label key={x.id}><input type="checkbox" checked={kit.evidence_ids.includes(x.id)} onChange={()=>setKit({...kit,evidence_ids:toggle(kit.evidence_ids,x.id)})}/>{x.title}</label>)}</fieldset><fieldset><legend>Timeline basis</legend>{timeline.map(x=><label key={x.id}><input type="checkbox" checked={kit.timeline_ids.includes(x.id)} onChange={()=>setKit({...kit,timeline_ids:toggle(kit.timeline_ids,x.id)})}/>{x.title}</label>)}</fieldset></div><textarea aria-label="Private Action Kit note" placeholder="Optional internal reviewer note — never exported" value={kit.internal_note} onChange={e=>setKit({...kit,internal_note:e.target.value})}/><label><input type="checkbox" checked={kit.approved} onChange={e=>setKit({...kit,approved:e.target.checked})}/> Approved and publishable</label><button disabled={saving}>Save Action Kit revision</button>
    </form></section>
    <section className="reviewer-block"><h3>Findings</h3><form className="reviewer-inline-form" onSubmit={(e)=>submit(e,"findings",finding,()=>setFinding(emptyFinding))}>
      <input aria-label="Finding title" placeholder="Finding title" required value={finding.title} onChange={(e)=>setFinding({...finding,title:e.target.value})}/>
      <select aria-label="Finding type" value={finding.finding_type} onChange={(e)=>setFinding({...finding,finding_type:e.target.value as ReviewerFinding["finding_type"]})}><option value="risk">Risk</option><option value="strength">Strength</option></select>
      <select aria-label="Severity" value={finding.severity} onChange={(e)=>setFinding({...finding,severity:e.target.value as ReviewerFinding["severity"]})}>{["critical","high","medium","low"].map(x=><option key={x}>{x}</option>)}</select>
      <textarea aria-label="Finding summary" placeholder="Summary" required value={finding.summary} onChange={(e)=>setFinding({...finding,summary:e.target.value})}/>
      <textarea aria-label="Recommended resolution" placeholder="Recommended resolution" required value={finding.recommended_resolution} onChange={(e)=>setFinding({...finding,recommended_resolution:e.target.value})}/>
      <textarea aria-label="Internal reviewer notes" placeholder="Internal reviewer notes — never exported" value={finding.internal_notes} onChange={(e)=>setFinding({...finding,internal_notes:e.target.value})}/>
      <div className="reviewer-reference-grid"><fieldset><legend>Supporting evidence</legend>{evidence.map(x=><label key={x.id}><input type="checkbox" checked={finding.evidence_ids.includes(x.id)} onChange={()=>setFinding({...finding,evidence_ids:toggle(finding.evidence_ids,x.id)})}/>{x.title}</label>)}</fieldset><fieldset><legend>Related timeline events</legend>{timeline.map(x=><label key={x.id}><input type="checkbox" checked={finding.timeline_ids.includes(x.id)} onChange={()=>setFinding({...finding,timeline_ids:toggle(finding.timeline_ids,x.id)})}/>{x.title}</label>)}</fieldset></div>
      <label>Confidence <select value={finding.confidence} onChange={(e)=>setFinding({...finding,confidence:e.target.value as ReviewerFinding["confidence"]})}>{["high","medium","low"].map(x=><option key={x}>{x}</option>)}</select></label><label><input type="checkbox" checked={finding.approved} onChange={(e)=>setFinding({...finding,approved:e.target.checked})}/> Approved for packet</label><button disabled={saving}>Add finding</button>
    </form><div className="reviewer-table" role="table">{workspace.findings.map(x=><article key={x.id}><div><strong>{x.title}</strong><span className={`reviewer-severity reviewer-severity--${x.severity}`}>{x.severity}</span></div><p>{x.summary}</p><small>{x.evidence_ids.length} evidence · {x.timeline_ids.length} events · {x.confidence} confidence{x.approved?" · approved":""}</small><button type="button" onClick={()=>setFinding({...x})}>Edit inline</button>{finding.id===x.id&&<button disabled={saving} type="button" onClick={()=>void save("findings",finding,()=>setFinding(emptyFinding),x.id)}>Save revision</button>}</article>)}</div></section>
    <section className="reviewer-block"><h3>Open Questions</h3><form className="reviewer-inline-form" onSubmit={(e)=>submit(e,"questions",question,()=>setQuestion(emptyQuestion),question.id)}><input required placeholder="Question" value={question.question} onChange={e=>setQuestion({...question,question:e.target.value})}/><textarea required placeholder="Why it matters" value={question.why_it_matters} onChange={e=>setQuestion({...question,why_it_matters:e.target.value})}/><textarea required placeholder="Evidence requested" value={question.evidence_requested} onChange={e=>setQuestion({...question,evidence_requested:e.target.value})}/><input required placeholder="Assigned reviewer" value={question.assigned_reviewer} onChange={e=>setQuestion({...question,assigned_reviewer:e.target.value})}/><select value={question.status} onChange={e=>setQuestion({...question,status:e.target.value})}>{["open","waiting","answered","closed"].map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={question.publishable} onChange={e=>setQuestion({...question,publishable:e.target.checked})}/> Publishable</label><button disabled={saving}>{question.id?"Save revision":"Add question"}</button></form><ul className="reviewer-list">{workspace.questions.map(x=><li key={x.id}><strong>{x.question}</strong><span>{x.status} · {x.assigned_reviewer}</span><button type="button" onClick={()=>setQuestion({...x})}>Edit inline</button></li>)}</ul></section>
    <section className="reviewer-block"><h3>Recommended Next Actions</h3><form className="reviewer-inline-form" onSubmit={(e)=>submit(e,"actions",action,()=>setAction(emptyAction),action.id)}><select value={action.priority} onChange={e=>setAction({...action,priority:e.target.value})}>{["critical","high","medium","low"].map(x=><option key={x}>{x}</option>)}</select><textarea required placeholder="Description" value={action.description} onChange={e=>setAction({...action,description:e.target.value})}/><textarea required placeholder="Estimated impact" value={action.estimated_impact} onChange={e=>setAction({...action,estimated_impact:e.target.value})}/><input required placeholder="Responsible party" value={action.responsible_party} onChange={e=>setAction({...action,responsible_party:e.target.value})}/><input type="date" value={action.due_date??""} onChange={e=>setAction({...action,due_date:e.target.value||null})}/><fieldset><legend>Supporting evidence</legend>{evidence.map(x=><label key={x.id}><input type="checkbox" checked={action.evidence_ids.includes(x.id)} onChange={()=>setAction({...action,evidence_ids:toggle(action.evidence_ids,x.id)})}/>{x.title}</label>)}</fieldset><label><input type="checkbox" checked={action.approved} onChange={e=>setAction({...action,approved:e.target.checked})}/> Approved for packet</label><button disabled={saving}>{action.id?"Save revision":"Add action"}</button></form><ul className="reviewer-list">{workspace.actions.map(x=><li key={x.id}><strong>{x.description}</strong><span>{x.priority} · {x.responsible_party}{x.due_date?` · ${x.due_date}`:""}</span><button type="button" onClick={()=>setAction({...x})}>Edit inline</button></li>)}</ul></section>
    <div className="reviewer-split"><section className="reviewer-block"><h3>Reviewer Notes</h3><form className="reviewer-inline-form" onSubmit={(e)=>submit(e,"notes",note,()=>setNote({commentary:"",publishable:false}),note.id)}><textarea required placeholder="Persistent internal commentary" value={note.commentary} onChange={e=>setNote({...note,commentary:e.target.value})}/><label><input type="checkbox" checked={note.publishable} onChange={e=>setNote({...note,publishable:e.target.checked})}/> Explicitly publishable</label><button disabled={saving}>{note.id?"Save revision":"Add note"}</button></form>{workspace.notes.map(x=><blockquote key={x.id}>{x.commentary}<small>{x.publishable?"Publishable":"Internal only"}</small><button type="button" onClick={()=>setNote({...x})}>Edit inline</button></blockquote>)}</section><section className="reviewer-block"><h3>Revision History</h3><ol className="revision-timeline">{workspace.revisions.map(x=><li key={x.id}><strong>{x.object_type}</strong><span>{x.actor.name??"Reviewer"} · {new Date(x.timestamp).toLocaleString()}</span></li>)}</ol></section></div>
  </section>;
}
